services:
  harcstack-org:
    image: quay.io/librasteve/harcstack-org:latest
    container_name: harcstack-org
    expose:
      - "3000"
    networks:
      - webnet
    restart: unless-stopped

  cragcli-info:
    image: quay.io/librasteve/cragcli-info:latest
    container_name: cragcli-info
    expose:
      - "3000"
    networks:
      - webnet
    restart: unless-stopped

  slangify-org:
    image: quay.io/librasteve/slangify-org:latest
    container_name: slangify-org
    expose:
      - "3000"
    networks:
      - webnet
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - harcstack-org
      - cragcli-info
      - slangify-org
    networks:
      - webnet
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  webnet:

